beta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('blog/', views.blog, name='blog'),
    path('search/', views.search, name="search"),
    path('blog/<slug:slug>/', views.post_detail, name="post_detail_url"),
    path('blog/<slug:slug>/leave_comment', views.comment, name='comment'),
    path('category/<slug:slug>/', views.category_detail, name="category_detail_url"),
    path('register/', views.register, name="register"),
    path('send-feedback/', views.feedback, name="feedback"),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.shortcuts import reverse

class Category(models.Model):
    title = models.CharField('Имя категории', max_length=255)
    image = models.ImageField('Картинка', blank=True, null=True, upload_to="categories/")
    slug = models.SlugField('Ссылка', unique=True)

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def get_absolute_url(self):
        return reverse('category_detail_url', kwargs={'slug':self.slug})

    def __str__(self):
        return self.title

class Post(models.Model):
    title = models.CharField('Заголовок', max_length=255)
    image = models.ImageField("Картинка", blank=True, null=True, upload_to="posts/")
    slug = models.SlugField("Ссылка", unique=True)
    summary = models.TextField("Краткое описание")
    text = models.TextField("Текст")
    category = models.ForeignKey(Category, null=True, on_delete = models.CASCADE, verbose_name = "Категория")
    date = models.DateTimeField('Дата', default=timezone.now)

    class Meta:
        verbose_name = "Новость"
        verbose_name_plural = "Новости"

    def get_absolute_url(self): 
        return reverse('post_detail_url', kwargs={'slug':self.slug})
    
    def __str__(self):  
        return self.title

class Comment(models.Model):
    author_name = models.CharField('Имя автора', max_length=255)
    text = models.TextField("Текст")
    post = models.ForeignKey(Post, null=True, on_delete = models.CASCADE, verbose_name = "Пост")
    date = models.DateTimeField('Дата', default=timezone.now)

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"
    
    def __str__(self):  
        return self.author_name

class FeedBack(models.Model):
    name = models.CharField('Имя отправителя', max_length=255)
    phone = models.CharField('Телефон', max_length=255)
    email = models.CharField('Email', max_length=255)
    text = models.TextField('Сообщение')
    date = models.DateTimeField('Дата', default=timezone.now)

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = 'Сообщения'

    def __str__(self):
        return self.name

blog/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    username = forms.CharField(label='Никнейм', required=True, widget=forms.TextInput(attrs={'class':'form-control footer-input margin-b-20'}))
    password1 = forms.CharField(label='Пароль', required=True, widget=forms.PasswordInput(attrs={'class':'form-control footer-input margin-b-20'}))
    password2 = forms.CharField(label='Подтверждение', required=True, widget=forms.PasswordInput(attrs={'class':'form-control footer-input margin-b-20'}))
    email = forms.EmailField(label='Email', required=True, widget=forms.TextInput(attrs={'class':'form-control footer-input margin-b-20'}))
    first_name = forms.CharField(label='Имя', widget=forms.TextInput(attrs={'class':'form-control footer-input margin-b-20'}))
    last_name = forms.CharField(label='Фамилия', widget=forms.TextInput(attrs={'class':'form-control footer-input margin-b-20'})) 
    
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password1', 'password2',)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        if commit:
            user.save()
            return user

blog/views.py
from django.shortcuts import render, redirect, reverse
from django.http import Http404
from .models import Post, Category, Comment, FeedBack
from django.db.models import Q
from .forms import RegisterForm
from django.contrib.auth.models import User

def index(request):
    return render(request, 'blog/index.html')

def blog(request):
    news = Post.objects.order_by('-date')
    return render(request, 'blog/blog.html', {'news':news})

def search(request):
    query = request.GET.get('search')
    search_obj = Post.objects.filter(
        Q(title__icontains = query) | Q(summary__icontains = query)
    )
    context = {'query': query, 'search_obj': search_obj}
    return render(request, 'blog/search.html', context)

def post_detail(request, slug):
    post = Post.objects.get(slug__exact = slug)
    return render(request, 'blog/post_detail.html', {'post':post})

def category_detail(request, slug):
    category = Category.objects.get(slug__exact = slug)
    return render(request, 'blog/category_detail.html', {'category':category})

def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = RegisterForm()
    return render(request, 'blog/register.html', {'form':form})

def comment(request, slug):
    try:
        post = Post.objects.get(slug__exact = slug)
    except:
        raise Http404('Статья не найдена')
    if request.user.is_authenticated:
        user = request.user.first_name
        post.comment_set.create(
            author_name = user, text = request.POST.get('text')
        )
    else:
        post.comment_set.create(
            author_name = request.POST.get('name'), text = request.POST.get('text')
        )
    return redirect(reverse('post_detail_url', args = (slug,)))

def feedback(request):
    mail = FeedBack.objects.all()
    mail.create(
        name = request.POST.get('name'),
        phone = request.POST.get('phone'),
        email = request.POST.get('email'),
        text = request.POST.get('text')
    )
    return redirect('index')

blog/templates/blog/blog.html
{% extends 'blog/layout.html' %}
{% load static %}
{% block title %}
Новости
{% endblock %}

{% block content %}
    <section id="bg-big" class="container-fluid" style="background: url(' {% static 'img/bg-big.jpg' %} ')">
        <div id="hero" class="jumbotron jumbotron-fluid">
            <div class="container">
              <h1 class="display-4">Новости</h1>
              <p class="lead">Очень интересные новости</p>
            </div>
        </div>
    </section>
    <section class="container-fluid">
        <section class="container">
            <div class="row">
                <div class="col-md-9">
                  {% for post in news %}
                    <div class="card mb-3" style="max-width: 540px;">
                        <div class="row no-gutters">
                          <div class="col-md-4">
                          {% if post.image.url != null %}
                          <a href="{{post.get_absolute_url}}">
                            <img src="{{post.image.url}}" style="height: 200px; object-fit: cover" class="card-img" alt="...">
                          </a>
                          {% else %}
                          <a href="{{post.get_absolute_url}}">
                            <img src="{% static 'img/no-image.jpg' %}" alt="">
                          </a>
                          {% endif %}
                          </div>
                          <div class="col-md-8">
                            <div class="card-body">
                              <a href="{{post.get_absolute_url}}">
                                <h5 class="card-title">{{post.title}}</h5>
                                <em><a href="{{post.category.get_absolute_url}}">{{post.category.title}}</a></em>
                              </a>
                              <p class="card-text">{{post.summary}}</p>
                              <p class="card-text"><small class="text-muted">{{post.date|date:'d F Y|e'}}</small></p>
                            </div>
                          </div>
                        </div>
                    </div>
                  {% endfor %}
                </div>
                <aside class="col-md-3"></aside>
            </div>
        </section>
    </section>
{% endblock %}

blog/templates/blog/category_detail.html
{% extends 'blog/layout.html' %}
{% load static %}
{% block title %}
{{category.title}}
{% endblock %}

{% block content %}
    <section id="bg-big" class="container-fluid" style="background: url(' {{category.image.url}} ')">
        <div id="hero" class="jumbotron jumbotron-fluid">
            <div class="container">
              <h1 class="display-4">{{category.title}}</h1>
            </div>
        </div>
    </section>
    <section class="container-fluid">
        <section class="container">
            <div class="row">
                <div class="col-md-9">
                
                  {% for post in category.post_set.all %}
                    <div class="card mb-3" style="max-width: 540px;">
                        <div class="row no-gutters">
                          <div class="col-md-4">
                          {% if post.image.url != null %}
                            <img src="{{post.image.url}}" style="height: 200px; object-fit: cover" class="card-img" alt="...">
                          {% else %}
                            <img src="{% static 'img/no-image.jpg' %}" alt="">
                          {% endif %}
                          </div>
                          <div class="col-md-8">
                            <div class="card-body">
                              <h5 class="card-title">{{post.title}}</h5>
                              <em><a href="{{post.category.get_absolute_url}}">{{post.category.title}}</a></em>
                              <p class="card-text">{{post.summary}}</p>
                              <p class="card-text"><small class="text-muted">{{post.date|date:'d F Y|e'}}</small></p>
                            </div>
                          </div>
                        </div>
                    </div>
                  {% endfor %}
                  
                </div>
                <aside class="col-md-3"></aside>
            </div>
        </section>
    </section>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/layout.html' %}
{% block title %}
    Главная страница
{% endblock %}
{% block content %}
    <section class="container-fluid">
        <div class="container">
            {% if not user.is_authenticated %}
                <h1 style="text-align: center;">Ты пидор</h1>
            {% else %}
                <h1 style="text-align: center;">Ты зареган</h1>
            {% endif %}
        </div>
    </section>
{% endblock %}

blog/templates/blog/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'index' %}">Главная</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog' %}">Новости</a>
            </li>
           {% if not user.is_authenticated %}
           <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Войти</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'register' %}">Регистрация</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0" action="{% url 'search' %}" method="GET">
            <input class="form-control mr-sm-2" type="text" name="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
    <section class="content-fluid">
      <div class="row">
        <div class="col-md-6"></div>
        <div class="col-md-6">
          <form action="{% url 'feedback' %}" method="POST">
            {% csrf_token %}
            <p>
              <label for="">Ваше имя</label>
              <input type="text" name="name" class="form-control">
            </p>
            <p>
              <label for="">Телефон</label>
              <input type="text" name="phone" class="form-control">
            </p>
            <p>
              <label for="">Email</label>
              <input type="email" name="email" class="form-control">
            </p>
            <p>
              <label for="">Сообщение</label>
              <textarea name="text" class="form-control" id="" cols="30" rows="10"></textarea>
            </p>
            <button class="btn btn-danger">Отправить</button>
          </form>
        </div>
      </div>
    </section>
    <footer id="footer" style="background: #111;">
        <div class="copy" style="text-align: center; padding: 20px">
            <p style="margin: 0; color: white">Разработчик <a href="#" style="color: white">Эмиль Ерофеевский</a></p>
        </div>
    </footer>
    <script src="{% static 'js/JQuery.js' %}"></script>
    <script src="{% static 'js/poper.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

blog/templates/blog/post_detail.html
{% extends 'blog/layout.html' %}
{% load static %}
{% block title %}
{{post.title}}
{% endblock %}

{% block content %}
    <section id="bg-big" class="container-fluid" style="background: url(' {{post.image.url}} ')">
        <div id="hero" class="jumbotron jumbotron-fluid">
            <div class="container">
              <h1 class="display-4">{{post.title}}</h1>
              <p class="lead">{{post.summary}}</p>
            </div>
        </div>
    </section>
    <section class="container-fluid">
        <section class="container">
            <div class="row">
                <div class="col-md-9">
                    <p>{{post.title}}</p>
                    <em><a href="{{post.category.get_absolute_url}}">{{post.category.title}}</a></em>
                    <p><img src="{{post.image.url}}" alt=""></p>
                    <p>{{post.summary}}</p>
                    <p>{{post.text}}</p>
                    <p>{{post.date}}</p>
                    <hr>
                    <h2>Комментарии: {{post.comment_set.count}}</h2>
                    <h3>Оставьте комментарий</h3>
                    <form action="{% url 'comment' post.slug %}" method="POST">
                        {% csrf_token %}
                        {% if not user.is_authenticated %}
                        <p>
                            <input class="form-control" type="text" name="name" placeholder="Имя">
                        </p>
                        {% endif %}
                        <p>
                            <textarea class="form-control" name="text" id="" cols="30" rows="10"></textarea>
                        </p>
                        <button class="btn btn-primary">Комментировать</button>
                    </form>
                    {% for comment in post.comment_set.all %}
                        <p>{{comment.author_name}}</p>
                        <p>{{comment.text}}</p>
                        <p>{{comment.date|date:'d F Y|e'}}</p>
                    {% endfor %}
                </div>
                <aside class="col-md-3"></aside>
            </div>
        </section>
    </section>
{% endblock %}

blog/templates/blog/register.html
{% extends 'blog/layout.html' %}
{% load static %}
{% block title %}
Регистрация
{% endblock %}

{% block content %}
    <form action="{% url 'register' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button>Регистрация</button>
    </form>
{% endblock %}

blog/templates/blog/search.html
{% extends 'blog/layout.html' %}
{% load static %}
{% block title %}
Поиск по: {{query}}
{% endblock %}

{% block content %}
    <section id="bg-big" class="container-fluid" style="background: url(' {% static 'img/bg-big.jpg' %} ')">
        <div id="hero" class="jumbotron jumbotron-fluid">
            <div class="container">
              <h1 class="display-4">{{query}}</h1>
              <p class="lead">Новости по запросу: {{query}}</p>
            </div>
        </div>
    </section>
    <section class="container-fluid">
        <section class="container">
            <div class="row">
                <div class="col-md-9">
                
                  {% for post in search_obj %}
                    <div class="card mb-3" style="max-width: 540px;">
                        <div class="row no-gutters">
                          <div class="col-md-4">
                          {% if post.image.url != null %}
                            <img src="{{post.image.url}}" style="height: 200px; object-fit: cover" class="card-img" alt="...">
                          {% else %}
                            <img src="{% static 'img/no-image.jpg' %}" alt="">
                          {% endif %}
                          </div>
                          <div class="col-md-8">
                            <div class="card-body">
                              <h5 class="card-title">{{post.title}}</h5>
                              <p class="card-text">{{post.summary}}</p>
                              <p class="card-text"><small class="text-muted">{{post.date|date:'d F Y|e'}}</small></p>
                            </div>
                          </div>
                        </div>
                    </div>
                  {% endfor %}
                  
                </div>
                <aside class="col-md-3"></aside>
            </div>
        </section>
    </section>
{% endblock %}